### ISSUE TITLE
Is TOAD available for installation outside UNF?

### ISSUE THREAD

**Issue by dorianps** [UNFmontreal/toad#278]
Is TOAD available for installation outside UNF, and if yes, how can it be installed?

Since I am here, one more question. It is stated in the Readme that the software is still under development and shouldn't be used yet for "production". But I noticed it is being used in published papers. Is there a timeline for considering it "good to go"?

Dorian

**Comment by arnaudbore** [comment]
Hi Dorian,

Yes, TOAD is available for installation outside UNF **but** some parts of the pipeline are using private packages such as the post-processing tasks. We are currently working on a new pipeline that will be available on [CBRAIN](https://portal.cbrain.mcgill.ca/login) this year. In addition, we do not have enough people working on TOAD to be able to provide any kind of support **outside** UNF but If you find any collaborators here at UNF/CRIUGM we will offer support in order for you to be able to analyse your data using TOAD otherwise I would say you'll be on your own to install TOAD and make it work on your server knowing that not all the tasks will be available.

Best,
Arnaud

**Comment by arnaudbore** [comment]
Hi @dorianps,

I would encourage you to use our brand new pipeline: [Tractoflow](https://github.com/scilus/tractoflow)

Way more robust than toad here is the [documentation](https://tractoflow-documentation.readthedocs.io/en/latest/)  

Best,
Arnaud

**Comment by dorianps** [comment]
Thank you.
